# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pharmacist_support.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pharmacist_support.proto',
  package='pharmacist_support',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18pharmacist_support.proto\x12\x12pharmacist_support\"(\n\x08\x44rugPair\x12\r\n\x05\x64rugA\x18\x01 \x01(\t\x12\r\n\x05\x64rugB\x18\x02 \x01(\t\"E\n\x17\x44rugInteractionResponse\x12\x18\n\x10interaction_type\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\"\x18\n\x08\x44rugName\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x0f\x41lternativeDrug\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x65\x66\x66icacy_score\x18\x02 \x01(\x02\"U\n\x18\x41lternativeDrugsResponse\x12\x39\n\x0c\x61lternatives\x18\x01 \x03(\x0b\x32#.pharmacist_support.AlternativeDrug2\xdc\x01\n\x11PharmacistSupport\x12\x62\n\x15\x46\x65tchDrugInteractions\x12\x1c.pharmacist_support.DrugPair\x1a+.pharmacist_support.DrugInteractionResponse\x12\x63\n\x15\x46\x65tchAlternativeDrugs\x12\x1c.pharmacist_support.DrugName\x1a,.pharmacist_support.AlternativeDrugsResponseb\x06proto3'
)




_DRUGPAIR = _descriptor.Descriptor(
  name='DrugPair',
  full_name='pharmacist_support.DrugPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='drugA', full_name='pharmacist_support.DrugPair.drugA', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drugB', full_name='pharmacist_support.DrugPair.drugB', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=88,
)


_DRUGINTERACTIONRESPONSE = _descriptor.Descriptor(
  name='DrugInteractionResponse',
  full_name='pharmacist_support.DrugInteractionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interaction_type', full_name='pharmacist_support.DrugInteractionResponse.interaction_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='severity', full_name='pharmacist_support.DrugInteractionResponse.severity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=159,
)


_DRUGNAME = _descriptor.Descriptor(
  name='DrugName',
  full_name='pharmacist_support.DrugName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pharmacist_support.DrugName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=185,
)


_ALTERNATIVEDRUG = _descriptor.Descriptor(
  name='AlternativeDrug',
  full_name='pharmacist_support.AlternativeDrug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pharmacist_support.AlternativeDrug.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='efficacy_score', full_name='pharmacist_support.AlternativeDrug.efficacy_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=242,
)


_ALTERNATIVEDRUGSRESPONSE = _descriptor.Descriptor(
  name='AlternativeDrugsResponse',
  full_name='pharmacist_support.AlternativeDrugsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alternatives', full_name='pharmacist_support.AlternativeDrugsResponse.alternatives', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=329,
)

_ALTERNATIVEDRUGSRESPONSE.fields_by_name['alternatives'].message_type = _ALTERNATIVEDRUG
DESCRIPTOR.message_types_by_name['DrugPair'] = _DRUGPAIR
DESCRIPTOR.message_types_by_name['DrugInteractionResponse'] = _DRUGINTERACTIONRESPONSE
DESCRIPTOR.message_types_by_name['DrugName'] = _DRUGNAME
DESCRIPTOR.message_types_by_name['AlternativeDrug'] = _ALTERNATIVEDRUG
DESCRIPTOR.message_types_by_name['AlternativeDrugsResponse'] = _ALTERNATIVEDRUGSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrugPair = _reflection.GeneratedProtocolMessageType('DrugPair', (_message.Message,), {
  'DESCRIPTOR' : _DRUGPAIR,
  '__module__' : 'pharmacist_support_pb2'
  # @@protoc_insertion_point(class_scope:pharmacist_support.DrugPair)
  })
_sym_db.RegisterMessage(DrugPair)

DrugInteractionResponse = _reflection.GeneratedProtocolMessageType('DrugInteractionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRUGINTERACTIONRESPONSE,
  '__module__' : 'pharmacist_support_pb2'
  # @@protoc_insertion_point(class_scope:pharmacist_support.DrugInteractionResponse)
  })
_sym_db.RegisterMessage(DrugInteractionResponse)

DrugName = _reflection.GeneratedProtocolMessageType('DrugName', (_message.Message,), {
  'DESCRIPTOR' : _DRUGNAME,
  '__module__' : 'pharmacist_support_pb2'
  # @@protoc_insertion_point(class_scope:pharmacist_support.DrugName)
  })
_sym_db.RegisterMessage(DrugName)

AlternativeDrug = _reflection.GeneratedProtocolMessageType('AlternativeDrug', (_message.Message,), {
  'DESCRIPTOR' : _ALTERNATIVEDRUG,
  '__module__' : 'pharmacist_support_pb2'
  # @@protoc_insertion_point(class_scope:pharmacist_support.AlternativeDrug)
  })
_sym_db.RegisterMessage(AlternativeDrug)

AlternativeDrugsResponse = _reflection.GeneratedProtocolMessageType('AlternativeDrugsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALTERNATIVEDRUGSRESPONSE,
  '__module__' : 'pharmacist_support_pb2'
  # @@protoc_insertion_point(class_scope:pharmacist_support.AlternativeDrugsResponse)
  })
_sym_db.RegisterMessage(AlternativeDrugsResponse)



_PHARMACISTSUPPORT = _descriptor.ServiceDescriptor(
  name='PharmacistSupport',
  full_name='pharmacist_support.PharmacistSupport',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=332,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchDrugInteractions',
    full_name='pharmacist_support.PharmacistSupport.FetchDrugInteractions',
    index=0,
    containing_service=None,
    input_type=_DRUGPAIR,
    output_type=_DRUGINTERACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FetchAlternativeDrugs',
    full_name='pharmacist_support.PharmacistSupport.FetchAlternativeDrugs',
    index=1,
    containing_service=None,
    input_type=_DRUGNAME,
    output_type=_ALTERNATIVEDRUGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PHARMACISTSUPPORT)

DESCRIPTOR.services_by_name['PharmacistSupport'] = _PHARMACISTSUPPORT

# @@protoc_insertion_point(module_scope)
