# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pharmacist_support_pb2 as pharmacist__support__pb2


class PharmacistSupportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchDrugInteractions = channel.unary_unary(
                '/pharmacist_support.PharmacistSupport/FetchDrugInteractions',
                request_serializer=pharmacist__support__pb2.DrugPair.SerializeToString,
                response_deserializer=pharmacist__support__pb2.DrugInteractionResponse.FromString,
                )
        self.FetchAlternativeDrugs = channel.unary_unary(
                '/pharmacist_support.PharmacistSupport/FetchAlternativeDrugs',
                request_serializer=pharmacist__support__pb2.DrugName.SerializeToString,
                response_deserializer=pharmacist__support__pb2.AlternativeDrugsResponse.FromString,
                )


class PharmacistSupportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchDrugInteractions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAlternativeDrugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PharmacistSupportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchDrugInteractions': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchDrugInteractions,
                    request_deserializer=pharmacist__support__pb2.DrugPair.FromString,
                    response_serializer=pharmacist__support__pb2.DrugInteractionResponse.SerializeToString,
            ),
            'FetchAlternativeDrugs': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAlternativeDrugs,
                    request_deserializer=pharmacist__support__pb2.DrugName.FromString,
                    response_serializer=pharmacist__support__pb2.AlternativeDrugsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacist_support.PharmacistSupport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PharmacistSupport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchDrugInteractions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacist_support.PharmacistSupport/FetchDrugInteractions',
            pharmacist__support__pb2.DrugPair.SerializeToString,
            pharmacist__support__pb2.DrugInteractionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchAlternativeDrugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacist_support.PharmacistSupport/FetchAlternativeDrugs',
            pharmacist__support__pb2.DrugName.SerializeToString,
            pharmacist__support__pb2.AlternativeDrugsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
