# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='public_health.proto',
  package='public_health',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13public_health.proto\x12\rpublic_health\"\x07\n\x05\x45mpty\"8\n\x0c\x41\x64verseEvent\x12\x16\n\x0esubstance_name\x18\x01 \x01(\t\x12\x10\n\x08reaction\x18\x02 \x01(\t\"D\n\x15\x41\x64verseEventsResponse\x12+\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1b.public_health.AdverseEvent\"9\n\x0fVaccineReaction\x12\x14\n\x0cvaccine_name\x18\x01 \x01(\t\x12\x10\n\x08symptoms\x18\x02 \x01(\t\"M\n\x18VaccineReactionsResponse\x12\x31\n\treactions\x18\x01 \x03(\x0b\x32\x1e.public_health.VaccineReaction\"@\n\x11PrescriptionStats\x12\x11\n\tdrug_name\x18\x01 \x01(\t\x12\x18\n\x10total_prescribed\x18\x02 \x01(\x05\"L\n\x19PrescriptionStatsResponse\x12/\n\x05stats\x18\x01 \x03(\x0b\x32 .public_health.PrescriptionStats2\x92\x02\n\x0cPublicHealth\x12P\n\x12\x46\x65tchAdverseEvents\x12\x14.public_health.Empty\x1a$.public_health.AdverseEventsResponse\x12V\n\x15\x46\x65tchVaccineReactions\x12\x14.public_health.Empty\x1a\'.public_health.VaccineReactionsResponse\x12X\n\x16\x46\x65tchPrescriptionStats\x12\x14.public_health.Empty\x1a(.public_health.PrescriptionStatsResponseb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='public_health.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=45,
)


_ADVERSEEVENT = _descriptor.Descriptor(
  name='AdverseEvent',
  full_name='public_health.AdverseEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='substance_name', full_name='public_health.AdverseEvent.substance_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reaction', full_name='public_health.AdverseEvent.reaction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=103,
)


_ADVERSEEVENTSRESPONSE = _descriptor.Descriptor(
  name='AdverseEventsResponse',
  full_name='public_health.AdverseEventsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='public_health.AdverseEventsResponse.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=173,
)


_VACCINEREACTION = _descriptor.Descriptor(
  name='VaccineReaction',
  full_name='public_health.VaccineReaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vaccine_name', full_name='public_health.VaccineReaction.vaccine_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symptoms', full_name='public_health.VaccineReaction.symptoms', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=232,
)


_VACCINEREACTIONSRESPONSE = _descriptor.Descriptor(
  name='VaccineReactionsResponse',
  full_name='public_health.VaccineReactionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reactions', full_name='public_health.VaccineReactionsResponse.reactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=311,
)


_PRESCRIPTIONSTATS = _descriptor.Descriptor(
  name='PrescriptionStats',
  full_name='public_health.PrescriptionStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='drug_name', full_name='public_health.PrescriptionStats.drug_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_prescribed', full_name='public_health.PrescriptionStats.total_prescribed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=377,
)


_PRESCRIPTIONSTATSRESPONSE = _descriptor.Descriptor(
  name='PrescriptionStatsResponse',
  full_name='public_health.PrescriptionStatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='public_health.PrescriptionStatsResponse.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=455,
)

_ADVERSEEVENTSRESPONSE.fields_by_name['events'].message_type = _ADVERSEEVENT
_VACCINEREACTIONSRESPONSE.fields_by_name['reactions'].message_type = _VACCINEREACTION
_PRESCRIPTIONSTATSRESPONSE.fields_by_name['stats'].message_type = _PRESCRIPTIONSTATS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AdverseEvent'] = _ADVERSEEVENT
DESCRIPTOR.message_types_by_name['AdverseEventsResponse'] = _ADVERSEEVENTSRESPONSE
DESCRIPTOR.message_types_by_name['VaccineReaction'] = _VACCINEREACTION
DESCRIPTOR.message_types_by_name['VaccineReactionsResponse'] = _VACCINEREACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['PrescriptionStats'] = _PRESCRIPTIONSTATS
DESCRIPTOR.message_types_by_name['PrescriptionStatsResponse'] = _PRESCRIPTIONSTATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.Empty)
  })
_sym_db.RegisterMessage(Empty)

AdverseEvent = _reflection.GeneratedProtocolMessageType('AdverseEvent', (_message.Message,), {
  'DESCRIPTOR' : _ADVERSEEVENT,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.AdverseEvent)
  })
_sym_db.RegisterMessage(AdverseEvent)

AdverseEventsResponse = _reflection.GeneratedProtocolMessageType('AdverseEventsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADVERSEEVENTSRESPONSE,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.AdverseEventsResponse)
  })
_sym_db.RegisterMessage(AdverseEventsResponse)

VaccineReaction = _reflection.GeneratedProtocolMessageType('VaccineReaction', (_message.Message,), {
  'DESCRIPTOR' : _VACCINEREACTION,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.VaccineReaction)
  })
_sym_db.RegisterMessage(VaccineReaction)

VaccineReactionsResponse = _reflection.GeneratedProtocolMessageType('VaccineReactionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _VACCINEREACTIONSRESPONSE,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.VaccineReactionsResponse)
  })
_sym_db.RegisterMessage(VaccineReactionsResponse)

PrescriptionStats = _reflection.GeneratedProtocolMessageType('PrescriptionStats', (_message.Message,), {
  'DESCRIPTOR' : _PRESCRIPTIONSTATS,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.PrescriptionStats)
  })
_sym_db.RegisterMessage(PrescriptionStats)

PrescriptionStatsResponse = _reflection.GeneratedProtocolMessageType('PrescriptionStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRESCRIPTIONSTATSRESPONSE,
  '__module__' : 'public_health_pb2'
  # @@protoc_insertion_point(class_scope:public_health.PrescriptionStatsResponse)
  })
_sym_db.RegisterMessage(PrescriptionStatsResponse)



_PUBLICHEALTH = _descriptor.ServiceDescriptor(
  name='PublicHealth',
  full_name='public_health.PublicHealth',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=458,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchAdverseEvents',
    full_name='public_health.PublicHealth.FetchAdverseEvents',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ADVERSEEVENTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FetchVaccineReactions',
    full_name='public_health.PublicHealth.FetchVaccineReactions',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_VACCINEREACTIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FetchPrescriptionStats',
    full_name='public_health.PublicHealth.FetchPrescriptionStats',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PRESCRIPTIONSTATSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBLICHEALTH)

DESCRIPTOR.services_by_name['PublicHealth'] = _PUBLICHEALTH

# @@protoc_insertion_point(module_scope)
